---
# - name: Install Consul
#   ansible.builtin.apt:
#     name: consul
#     state: present
#     update_cache: yes
#   ignore_errors: "{{ ansible_check_mode }}"

- name: Install unzip
  ansible.builtin.apt:
    name: unzip
    state: latest
  ignore_errors: "{{ ansible_check_mode }}"

# TODO: wait for fix of https://github.com/hashicorp/nomad/issues/15266
- name: install consul
  ansible.builtin.unarchive:
    dest: "/usr/bin/"
    src: "https://releases.hashicorp.com/consul/1.13.3/consul_1.13.3_linux_amd64.zip"
    mode: 0755
    remote_src: true
  when: not ansible_check_mode

- name: Ensure Consul config, data and certs dir exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ consul_config_dir }}"
    - "{{ consul_data_dir }}"
    - "{{ consul_certs_dir }}"

- name: Add Consul configurations
  ansible.builtin.template:
    dest: "{{ consul_config_dir }}/{{ item.dest }}"
    src: "{{ item.src }}"
  loop:
    - src: "consul.hcl.j2"
      dest: "consul.hcl"
    - src: "{{ node_type }}.hcl.j2"
      dest: "{{ node_type }}.hcl"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Copy consul CA cert over
  ansible.builtin.copy:
    dest: "{{ consul_certs_dir }}/consul_ca_cert.pem"
    src: "{{ local_temp_certs_dir }}/consul_ca_cert.pem"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Create {{ node_type }} TLS key and cert
  include: tls.yml

- block:
    - name: Create client ACL token
      include: acl.yml
      when: not ansible_check_mode
    - name: Setup DNS forwarding on client
      include: dns.yml
  when: node_type == "client"

- name: Copy consul systemd service
  ansible.builtin.template:
    dest: "/etc/systemd/system/consul.service"
    src: "consul.service.j2"

- name: Start Consul and ensure it starts on boot
  ansible.builtin.service:
    name: consul.service
    enabled: yes
    state: started
  ignore_errors: "{{ ansible_check_mode }}"
