---
- name: Ensure local certs dir exists
  ansible.builtin.file:
    path: "{{ local_temp_certs_dir }}"
    state: directory

- name: Set up CA certs
  include_tasks: ca.yml
  loop:
    - "consul"
    - "nomad"
