---
- name: Create server TLS key and cert
  include: tls.yml

- name: Copy Consul server agents config
  ansible.builtin.template:
    dest: "{{ consul_config_dir }}/server.hcl"
    src: server.hcl.j2
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

# TODO: use template for this service so we can use the consul_config_dir var
- name: Start Consul and ensure it starts on boot
  ansible.builtin.service:
    name: consul.service
    enabled: yes
    state: started
