---
- name: Install Caddy
  ansible.builtin.get_url:
    url: "{{ caddy_binary_url }}"
    dest: "/usr/bin/caddy" 
    mode: 0755
    owner: root
    group: root
  ignore_errors: "{{ ansible_check_mode }}"

- name: Ensure caddy config dir exists
  ansible.builtin.file:
    path: "{{ caddy_config_dir }}"
    state: directory

- name: Copy caddy systemd service
  ansible.builtin.template:
    dest: "/etc/systemd/system/caddy.service"
    src: "caddy.service.j2"

- name: Ensure Caddy starts on boot
  ansible.builtin.service:
    name: caddy.service
    enabled: yes
    state: started
    # this task fails with "permission denied" due to
    # some issue with systemd, this should fix that
    daemon_reexec: true
  ignore_errors: "{{ ansible_check_mode }}"
