---
- name: Install consul-template
  ansible.builtin.unarchive:
    src: "{{ consul_template_url }}"
    dest: "/usr/bin/"
    mode: 0755
    remote_src: true
  when: not ansible_check_mode

- name: Ensure consul-template config and templates dir exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: caddy
    group: caddy
  loop:
    - "{{ consul_template_config_dir }}"
    - "{{ consul_template_templates_dir }}"

- name: Copy consul-template config file
  ansible.builtin.template:
    src: consul-template.hcl.j2
    dest: "{{ consul_template_config_dir }}/consul-template.hcl"
    owner: caddy
    group: caddy
  ignore_errors: "{{ ansible_check_mode }}"

- name: Copy Caddyfile template
  ansible.builtin.template:
    src: Caddyfile.ctmpl.j2
    dest: "{{ consul_template_templates_dir }}/Caddyfile.ctmpl"
    # use a jinja2 header within the template file instead of this
    # using these params makes it so that variable interpolation in the template
    # doesn't work since that expects the variable to also use these delimiters
    # can also use lookup('vars') on each variable instead
    # variable_start_string: "[["
    # variable_end_string: "]]"
    owner: caddy
    group: caddy
  ignore_errors: "{{ ansible_check_mode }}"

- name: Copy consul-template systemd service file
  ansible.builtin.template:
    src: consul-template.service.j2
    dest: "/etc/systemd/system/consul-template.service"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Ensure consul-template starts on boot
  ansible.builtin.service:
    name: consul-template.service
    enabled: yes
    state: started
  ignore_errors: "{{ ansible_check_mode }}"
