---
- name: Generate private key for consul {{ node_type }} TLS cert
  community.crypto.openssl_privatekey:
    path: "{{ consul_certs_dir }}/consul_{{ node_type }}_tls_key.pem"

- name: Generate in-memory CSR for consul {{ node_type }} TLS cert
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ consul_certs_dir }}/consul_{{ node_type }}_tls_key.pem"
    common_name: "{{ node_type }}.{{ consul_datacenter }}.consul"
    subject_alt_name:
      - "DNS:{{ node_type }}.{{ consul_datacenter }}.consul"
      - "DNS:consul_{{ node_id }}.{{ node_type }}.{{ consul_datacenter }}.consul"
      - "DNS:localhost"
      - "IP:127.0.0.1"
    basic_constraints_critical: yes
    basic_constraints:
      - CA:FALSE
    key_usage_critical: yes
    key_usage:
      - digitalSignature
      - keyEncipherment
    # TODO: idk what keywords to use in this list
    # extended_key_usage:
    #   - TLS Web Server Authentication
    #   - TLS Web Client Authentication
  register: consul_csr

- name: Generate consul {{ node_type }} TLS cert from CSR with in-memory CA key
  community.crypto.x509_certificate:
    path: "{{ consul_certs_dir }}/consul_{{ node_type }}_tls_cert.pem"
    csr_content: "{{ consul_csr.csr }}"
    ownca_privatekey_content: "{{ consul_ca_key.privatekey }}"
    ownca_path: "{{ consul_certs_dir }}/consul_ca_cert.pem"
    provider: ownca
