---
- name: Install Consul
  ansible.builtin.apt:
    name: consul
    state: present
    update_cache: yes

- name: Ensure Consul config, data and certs dir exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
  loop:
    - "{{ consul_config_dir }}"
    - "{{ consul_data_dir }}"
    - "{{ consul_certs_dir }}"

- name: Add Consul configuration
  ansible.builtin.template:
    dest: "{{ consul_config_dir }}/consul.hcl"
    src: consul.hcl.j2
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

- name: Copy CA cert over
  ansible.builtin.copy:
    dest: "{{ consul_certs_dir }}/ca_cert.pem"
    src: "{{ local_temp_certs_dir }}/consul_ca_cert.pem"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
