---
- name: Create server TLS key and cert
  include: tls.yml

- name: Create consul ACL token
  include: consul-acl.yml

- name: Copy Nomad server agents config
  ansible.builtin.template:
    dest: "{{ nomad_config_dir }}/server.hcl"
    src: server.hcl.j2
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

# TODO: use template for this service so we can use the nomad_config_dir var
- name: Start Nomad and ensure it starts on boot
  ansible.builtin.service:
    name: nomad.service
    enabled: yes
    state: started
