---
- name: Generate private key for nomad {{ node_type }} TLS cert
  community.crypto.openssl_privatekey:
    path: "{{ nomad_certs_dir }}/nomad_{{ node_type }}_tls_key.pem"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Generate in-memory CSR for nomad {{ node_type }} TLS cert
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ nomad_certs_dir }}/nomad_{{ node_type }}_tls_key.pem"
    common_name: "{{ node_type }}.{{ nomad_region }}.nomad"
    subject_alt_name:
      - "DNS:{{ node_type }}.{{ nomad_region }}.nomad"
      - "DNS:localhost"
      - "IP:127.0.0.1"
      - "IP:{{ hostvars[inventory_hostname]['ansible_host'] | default(inventory_hostname) }}"
    basic_constraints_critical: yes
    basic_constraints:
      - CA:FALSE
    key_usage_critical: yes
    # https://github.com/ansible-collections/community.crypto/blob/a050250153596de36e83891b63f2f171c86b2b2a/plugins/module_utils/crypto/cryptography_support.py#L532
    key_usage:
      - digitalSignature
      - keyEncipherment
    # https://github.com/ansible-collections/community.crypto/blob/a050250153596de36e83891b63f2f171c86b2b2a/tests/integration/targets/x509_certificate_info/tasks/main.yml#L64
    extended_key_usage:
      - serverAuth
      - clientAuth
  register: nomad_csr

- name: Generate nomad {{ node_type }} TLS cert from CSR with in-memory CA key
  community.crypto.x509_certificate:
    path: "{{ nomad_certs_dir }}/nomad_{{ node_type }}_tls_cert.pem"
    csr_content: "{{ nomad_csr.csr }}"
    ownca_privatekey_content: "{{ lookup('file', local_temp_certs_dir + '/nomad_ca_key.pem') }}"
    ownca_path: "{{ nomad_certs_dir }}/nomad_ca_cert.pem"
    provider: ownca
  ignore_errors: "{{ ansible_check_mode }}"
