---
- name: Create CNI plugins dir
  ansible.builtin.file:
    path: "{{ nomad_cni_dir }}"
    state: directory

- name: Install CNI Plugins
  ansible.builtin.unarchive:
    src: "{{ nomad_cni_url }}"
    dest: "{{ nomad_cni_dir }}"
    remote_src: true
  when: not ansible_check_mode

- name: Allow iptables processing for bridge networks
  ansible.builtin.copy:
    dest: "/proc/sys/net/bridge/{{ item }}"
    content: "1"
  loop:
    - bridge-nf-call-arptables
    - bridge-nf-call-ip6tables
    - bridge-nf-call-iptables

- name: Ensure previous settings are preserved on restart
  ansible.posix.sysctl:
    key: "{{ item }}"
    value: "1"
    reload: yes
  loop:
    - net.bridge.bridge-nf-call-arptables
    - net.bridge.bridge-nf-call-ip6tables
    - net.bridge.bridge-nf-call-iptables
  when: not ansible_check_mode
