---
- name: Generate private key for nomad {{ node_type }} TLS cert
  community.crypto.openssl_privatekey:
    path: "{{ nomad_certs_dir }}/nomad_{{ node_type }}_tls_key.pem"

- name: Generate in-memory CSR for nomad {{ node_type }} TLS cert
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ nomad_certs_dir }}/nomad_{{ node_type }}_tls_key.pem"
    common_name: "{{ node_type }}.{{ nomad_region }}.nomad"
    subject_alt_name:
      - "DNS:{{ node_type }}.{{ nomad_region }}.nomad"
      - "DNS:localhost"
      - "IP:127.0.0.1"
    basic_constraints_critical: yes
    basic_constraints:
      - CA:FALSE
    key_usage_critical: yes
    key_usage:
      - digitalSignature
      - keyEncipherment
    # TODO: idk what keywords to use in this list
    # extended_key_usage:
    #   - TLS Web Server Authentication
    #   - TLS Web Client Authentication
  register: nomad_csr

- name: Generate nomad {{ node_type }} TLS cert from CSR with in-memory CA key
  community.crypto.x509_certificate:
    path: "{{ nomad_certs_dir }}/nomad_{{ node_type }}_tls_cert.pem"
    csr_content: "{{ nomad_csr.csr }}"
    ownca_privatekey_content: "{{ nomad_ca_key.privatekey }}"
    ownca_path: "{{ nomad_certs_dir }}/nomad_ca_cert.pem"
    provider: ownca
