---
- name: Install required packages for Docker on Ubuntu
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - gnupg
      - lsb-release
    state: latest
    update_cache: yes

- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present

- name: Install Docker
  ansible.builtin.apt:
    update_cache: yes
    name: 
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
      - containerd.io
    state: latest

- name: Create "docker" group
  ansible.builtin.group:
    name: docker
    state: present

- name: Add remote user to "docker" group
  ansible.builtin.user:
    name: "{{ username }}"
    groups: docker
    append: yes

- name: Ensure Docker daemons starts on boot
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - docker.service
    - containerd.service

- name: Install docker-compose (standalone)
  ansible.builtin.get_url:
    url: "{{ docker_compose_standalone_url }}"
    dest: /usr/bin/docker-compose
    mode: 0755
  when: docker_install_compose_standalone | bool
