---
- name: Build infrastructure
  hosts: localhost
  connection: local
  vars_files:
    - vars/main.yml
  vars:
    tfvars:
      bastion_username: "{{ terraform_var_bastion_username }}"
      ssh_key_name: "{{ terraform_var_ssh_key_name }}"
      network_ip_range: "{{ terraform_var_network_ip_range }}"
      subnet_ip_range: "{{ terraform_var_subnet_ip_range }}"
      loadbalancer_count: "{{ terraform_var_loadbalancer_count }}"
      server_node_count: "{{ terraform_var_server_node_count }}"
      client_node_count: "{{ terraform_var_client_node_count }}"

  tasks:
    - name: Ensure SSH key name is provided
      ansible.builtin.assert:
        that: terraform_var_ssh_key_name != ""
        fail_msg: "No SSH key name provided, please configure the 'terraform_var_ssh_key_name' variable"

    - name: Deploy infrastructure with terraform
      community.general.terraform:
        overwrite_init: no
        force_init: yes
        project_path: "{{ terraform_project_dir }}"
        state: present
        variables: "{{ tfvars }}"

    - name: Create tfvars file
      ansible.builtin.copy:
        content: "{{ tfvars | to_nice_json }}"
        dest: "{{ terraform_project_dir }}/terraform.tfvars.json"

    - name: Update inventory with inventory created by terraform
      ansible.builtin.meta: refresh_inventory

- import_playbook: provision.yml
