---
- name: Pre-provision checks
  hosts: localhost
  connection: local
  vars_files:
    - vars/main.yml
  tasks:
    - block:
        - name: Get username from user
          pause:
            prompt: "Enter username for user to be created on remote hosts"
          register: __username
        - name: set username fact
          set_fact:
            username: "{{ __username.user_input }}"
      when: username == ""

    - block:
      - set_fact:
          username: "noobis"
      - debug:
          msg: "No username provided for remote hosts, defaulted to 'noobis'"
      when: username == ""

    - block:
        - name: Get password from user
          pause:
            prompt: "Enter password for user to be created on remote hosts"
            echo: no
          register: __password
        - name: set password fact
          set_fact:
            password: "{{ __password.user_input }}"
      when: password == ""
      no_log: true

    - assert:
        that: password != ""
        fail_msg: "No password provided"

    - block:
        - name: Get host domain from user
          pause:
            prompt: "Enter host domain name for loadbalancer to use"
          register: __host_domain
        - name: set host domain fact
          set_fact:
            caddy_host_domain: "{{ __host_domain.user_input }}"
      when: caddy_host_domain == ""

    - assert:
        that: caddy_host_domain != ""
        fail_msg: "No host domain name provided"

    - block:
        - name: Get grafana password from user
          pause:
            prompt: "Enter password for grafana admin"
            echo: no
          register: __grafana_password
        - name: set grafana password fact
          set_fact:
            grafana_admin_password: "{{ __grafana_password.user_input }}"
      when: grafana_admin_password == ""
      no_log: true

    - block:
      - set_fact:
          grafana_admin_password: "admin"
      - debug:
          msg: "No admin password provided for grafana, defaulted to 'admin'"
      when: grafana_admin_password == ""

- name: Bootstrap all VMs
  hosts: all
  remote_user: root
  vars_files:
    - vars/main.yml
  roles:
    - base

- name: Create TLS keys and certs
  hosts: localhost
  connection: local
  vars_files:
    - vars/main.yml
  roles:
    - tls

- name: Setup server agents
  hosts: servers
  remote_user: "{{ username }}"
  become: true
  vars_files:
    - vars/main.yml
  vars:
    - node_type: "server"
  roles:
    - consul
    - nomad

- name: Setup client agents
  hosts: clients
  remote_user: "{{ username }}"
  become: true
  vars_files:
    - vars/main.yml
  vars:
    - node_type: "client"
  roles:
    - consul
    - docker
    - nomad

- name: Setup loadbalancers
  hosts: loadbalancers
  remote_user: "{{ username }}"
  become: true
  vars_files:
    - vars/main.yml
  vars:
    - node_type: "client"
  roles:
    - consul
    - caddy
    - monitoring
