---
- name: Pre-provision checks
  hosts: localhost
  connection: local
  vars_files:
    - vars/main.yml
  tasks:
    - name: Ensure host domain name for caddy is provided
      ansible.builtin.assert:
        that: caddy_host_domain != ""
        fail_msg: "No host domain name provided, please configure the 'caddy_host_domain' variable"

- name: Bootstrap all VMs
  hosts: all
  remote_user: root
  vars_files:
    - vars/main.yml
  roles:
    - base

- name: Create TLS keys and certs
  hosts: localhost
  connection: local
  vars_files:
    - vars/main.yml
  roles:
    - tls

- name: Setup server agents
  hosts: servers
  remote_user: "{{ username }}"
  vars_files:
    - vars/main.yml
  vars:
    - node_type: "server"
  roles:
    - consul-install
    - consul-server
    - nomad-install
    - nomad-server

- name: Setup client agents
  hosts: clients
  remote_user: "{{ username }}"
  vars_files:
    - vars/main.yml
  vars:
    - node_type: "client"
  roles:
    - consul-install
    - consul-client
    - docker
    - nomad-install
    - nomad-client

- name: Setup loadbalancers
  hosts: loadbalancers
  remote_user: "{{ username }}"
  vars_files:
    - vars/main.yml
  vars:
    - node_type: "client"
  roles:
    - consul-install
    - consul-client
    - caddy
