---
- name: create nodeexp system group
  ansible.builtin.group:
    name: nodeexp
    state: present
    system: true

- name: create nodeexp system user
  ansible.builtin.user:
    name: nodeexp
    group: nodeexp
    shell: "/usr/sbin/nologin"
    system: true
    create_home: false

- name: get node-exporter archive
  ansible.builtin.unarchive:
    dest: "/tmp/"
    src: "{{ node_exporter_url }}"
    remote_src: true
  when: not ansible_check_mode

- name: Install node-exporter binary
  ansible.builtin.copy:
    dest: "/usr/bin/node_exporter"
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    remote_src: true
    mode: 0755
  ignore_errors: "{{ ansible_check_mode }}"

- name: Copy node-exporter systemd service
  ansible.builtin.template:
    dest: "/etc/systemd/system/node-exporter.service"
    src: "node-exporter.service.j2"

- name: Start node-exporter and ensure it starts on boot
  ansible.builtin.service:
    name: node-exporter.service
    enabled: yes
    state: started
  ignore_errors: "{{ ansible_check_mode }}"
