---
# using this to make sure the server is running and healthy
# idk if the leader will ever be needed but it's handy to have
- name: Find consul RAFT leader while checking cluster health
  ansible.builtin.uri:
    url: "https://{{ consul_first_server.ip }}:8501/v1/status/leader"
    ca_path:  "{{ consul_certs_dir }}/ca_cert.pem"
    client_key: "{{ consul_certs_dir }}/client_tls_key.pem"
    client_cert: "{{ consul_certs_dir }}/client_tls_cert.pem"
    return_content: yes
  register: consul_leader
  until: (consul_leader.json is defined) and (consul_leader.json != '')
  retries: 20
  delay: 6

- name: Create consul policy for DNS
  ansible.builtin.uri:
    method: PUT
    url: "https://{{ consul_first_server.ip }}:8501/v1/acl/policy"
    ca_path:  "{{ consul_certs_dir }}/ca_cert.pem"
    client_key: "{{ consul_certs_dir }}/client_tls_key.pem"
    client_cert: "{{ consul_certs_dir }}/client_tls_cert.pem"
    return_content: yes
    headers:
      X-Consul-Token: "{{ hostvars[consul_first_server.hostname]['consul_acl_bootstrap_token'] }}"
    body_format: json
    body:
      Name: dns-policy
      Description: "Policy to allow DNS lookups from the node serving DNS requests"
      Rules: |
        node_prefix "" {
          policy = "read"
        }
        service_prefix "" {
          policy = "read"
        }
  register: consul_dns_policy
  run_once: true

- name: Create ACL token
  ansible.builtin.uri:
    method: PUT
    url: "https://{{ consul_first_server.ip }}:8501/v1/acl/token"
    ca_path:  "{{ consul_certs_dir }}/ca_cert.pem"
    client_key: "{{ consul_certs_dir }}/client_tls_key.pem"
    client_cert: "{{ consul_certs_dir }}/client_tls_cert.pem"
    headers:
      X-Consul-Token: "{{ hostvars[consul_first_server.hostname]['consul_acl_bootstrap_token'] }}"
    body_format: json
    body:
      SecretID: "{{ consul_acl_client_token }}"
      Description: "ACL token for {{ consul_node_name }}"
      Policies:
        - ID: "{{ consul_dns_policy.json.ID }}"
      NodeIdentities:
        - NodeName: "{{ consul_node_name }}"
          Datacenter: "{{ consul_datacenter }}"
