---
- name: Create server TLS key and cert
  include: tls.yml

- name: Create consul ACL token
  include: consul-acl.yml

- name: Copy Nomad client agents config
  ansible.builtin.template:
    dest: "{{ nomad_config_dir }}/client.hcl"
    src: client.hcl.j2
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

- name: Create CNI plugins dir
  ansible.builtin.file:
    path: "{{ nomad_cni_dir }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Install CNI Plugins
  ansible.builtin.unarchive:
    src: "{{ nomad_cni_url }}"
    dest: "{{ nomad_cni_dir }}"
    remote_src: true

- name: Allow iptables processing for bridge networks
  ansible.builtin.copy:
    dest: "/proc/sys/net/bridge/{{ item }}"
    content: "1"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
  loop:
    - bridge-nf-call-arptables
    - bridge-nf-call-ip6tables
    - bridge-nf-call-iptables

- name: Ensure previous settings are preserved on restart
  ansible.posix.sysctl:
    key: "{{ item }}"
    value: "1"
    reload: yes
  loop:
    - net.bridge.bridge-nf-call-arptables
    - net.bridge.bridge-nf-call-ip6tables
    - net.bridge.bridge-nf-call-iptables

# TODO: use template for this service so we can use the nomad_config_dir var
- name: Start Nomad and ensure it starts on boot
  ansible.builtin.service:
    name: nomad.service
    enabled: yes
    state: started
