name: ansible-lint
on: [push, pull_request]

jobs:
  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # needed for ansible-lint's progressive mode to work

      - name: Run ansible-lint
        uses: ansible/ansible-lint-action@v6
        # with:
        #   path: "playbooks/"  # <-- only one value is allowed
